<?php

return array (
  'Dashboard' => 'الرئيسية',
  'Get_my_IP' => 'الاي بى',
  'Desk_queue' => 'انتظار الاستقبال',
  'Doctors_queue' => 'قائمة انتظار الأطباء',
  'Authorization' => 'تفويض',
  'Clinics' => 'العيادات',
  'Desk_queue_History' => 'سجل قائمة انتظار المكتب',
  'Desks' => 'الاستقبال',
  'Desks_Reports' => 'تقارير الاستقبال',
  'Doctors' => 'الاطباء',
  'Doctors_Reports' => 'تقارير الاطباء',
  'Doctors_queue_History' => 'سجل قائمة انتظار الأطباء',
  'Floors' => 'الادوار',
  'Ganzory_Resources' => 'موارد الجنزورى',
  'Patients' => 'المرضى',
  'Permission_Groups' => 'مجموعات الصلاحيات',
  'Permissions' => 'الصلاحيات',
  'Printers' => 'الطابعات',
  'Queues' => 'قائمة انتظار',
  'Queues_History' => 'سجل قائمة الانتظار',
  'Reception_Areas' => 'منطقة الاستقبال',
  'Reports' => 'التقارير',
  'Reservations' => 'الحجوزات',
  'Resources' => 'الموارد',
  'Rooms' => 'الغرف',
  'Roles' => 'الأدوار',
  'Schedules' => 'الجداول',
  'Screens' => 'الشاشات',
  'Security' => 'الامن',
  'Settings' => 'الاعدادات',
  'Specialities' => 'التخصصات',
  'Speciality_to_area' => 'التخصص بالنسبة للمنطقة',
  'Translations' => 'الترجمة',
  'User_actions' => 'إجراءات المستخدم',
  'User_logins' => 'تسجيلات دخول المستخدم',
  'Users' => 'المستخدمين',
  'Logs' => 'السجلات',
);
